# Generated by Django 4.1 on 2022-08-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='isPublished',
            field=models.BooleanField(default=None),
        ),
    ]
