# Generated by Django 4.0.6 on 2022-08-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='add_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='pub_date',
            field=models.DateField(default=None),
        ),
    ]
