# Generated by Django 4.1 on 2022-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0002_alter_caroffer_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='isDeleted',
            field=models.BooleanField(default=None),
        ),
    ]
