# Generated by Django 4.0.6 on 2022-08-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0002_alter_caroffer_add_date_alter_caroffer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='pub_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
