# Generated by Django 4.1 on 2023-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0002_caroffer_isdeleted_alter_caroffer_car_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroffer',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
