# Generated by Django 4.1 on 2022-08-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0005_alter_caroffer_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
