# Generated by Django 4.1 on 2022-08-29 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0006_alter_caroffer_isdeleted_alter_caroffer_ispublished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='car_category',
            field=models.CharField(choices=[('MOTORCYCLE', 'motocykl'), ('CAR', 'osobowy'), ('TRUCK', 'ciężarowy')], max_length=15),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='cubic_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='description',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='fuel_category',
            field=models.CharField(choices=[('PETROL', 'benzyna'), ('DIESEL', 'diesel'), ('LPG', 'lpg')], max_length=15),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='manufacture_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='power',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='title',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinValueValidator(4)]),
        ),
    ]
