# Generated by Django 4.1 on 2022-08-29 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0008_alter_caroffer_description_alter_caroffer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='description',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='caroffer',
            name='title',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
