# Generated by Django 4.1 on 2022-08-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0009_alter_caroffer_description_alter_caroffer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='pub_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
