# Generated by Django 4.1 on 2022-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motosell_app', '0010_alter_caroffer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroffer',
            name='fuel_category',
            field=models.CharField(choices=[('Benzyna', 'benzyna'), ('Diesel', 'diesel'), ('LPG', 'lpg')], max_length=15),
        ),
    ]
